name: Generate Cred Instance
on:
  # Trigger on merging to master.
  push:
    branches:
      - master
  # As well as every 24 hours (at 0:00 UTC).
  schedule:
    - cron: 0 0 * * *

jobs:
  GenerateCredInstance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false # Required to make github pages deployment work correctly
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Data # Cache SourceCred Data, invalidating if any of the config changes or the SC version is updated
        uses: actions/cache@v2.1.7
        with:
          path: "**/cache"
          key: SC-${{ runner.os }}-${{ hashFiles('**/config.json', '**/sourcecred.json', '**/yarn.lock') }}

      - name: Install Packages üîß
        run: |
          yarn --frozen-lockfile

      - name: Load Data and Compute Cred üßÆ
        run: |
          yarn sourcecred go
          node scripts/wolf-turtle-bear.js
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Generate Frontend üèó
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          yarn sourcecred site
          yarn sourcecred analysis
          rm -rf ./site/{output,data,config,sourcecred.json}
          cp -r ./{output,data,config,sourcecred.json,package.json} ./site/

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
          SINGLE-COMMIT: true
